# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                #client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                #bucket: '%env(AWS_S3_BUCKET_NAME)%'
                #prefix: 'optional/path/prefix'
                #streamReads: true
                directory: '%kernel.project_dir%/var/storage/default'
                #'%kernel.project_dir%/public/images/uploads'
