# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    # the IP address (or range) of your proxy
    #trusted_proxies: '192.0.0.1,10.0.0.0/8'
    # trust *all* "X-Forwarded-*" headers
    #trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    # or, if your proxy instead uses the "Forwarded" header
    #trusted_headers: [ 'forwarded' ]
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        #handler_id: session.handler.mongo
        #cookie_lifetime: 2592000 # optional, it is set to 30 days here
        #gc_maxlifetime: 2592000 # optional, it is set to 30 days here

#services:
    # ...
    #mongo_client:
        #class: MongoClient
        # if using a username and password
        #arguments: ['mongo:mongophp@cluster0.mz4dm.mongodb.net/?retryWrites=true&w=majority']
    #session.handler.mongo:
        #class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        #arguments:
           # - '@mongo_client'
           # - { database: 'cluster0.mz4dm.mongodb.net.User1', collection: 'sessions' }

    #esi: true
    #fragments: true
    #php_errors:
        #log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
